# Generated by Django 4.0.1 on 2022-02-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_info_alter_payment_num_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_num',
            name='phone_num',
            field=models.BigIntegerField(),
        ),
    ]
